using System;
using System.Collections.Generic;

using ZStewart.KOSLisp.Types.TypeCategories;

namespace ZStewart.KOSLisp.Types {
  /// <summary>
  /// Base class for lisp types.
  ///
  /// (this file contains just the bare object with public instance fields).
  /// </summary>
  public partial class LispType : LispObject {
    /// <summary>
    /// The name of this type.
    /// </summary>
    public string __name__;
    /// <summary>
    /// The base classes of this type. (An ICons).
    /// </summary>
    public LispObject __bases__;
    /// <summary>
    /// Function for creating a new instance of this type. Inherited.
    /// </summary>
    public Func<LispObject, LispObject, LispObject> __new__;
    /// <summary>
    /// Function for initializing data in this type. Inherited.
    /// </summary>
    public Func<LispObject, LispObject, LispObject> __init__;
    /// <summary>
    /// Function for calling this type. Inherited.
    /// </summary>
    public CallFunc __call__;
    /// <summary>
    /// Function to look up a property of this type. Inherited.
    /// </summary>
    public Func<LispObject, LispObject, LispObject> __getattr__;
    /// <summary>
    /// Function to set a property of this type. Inherited.
    /// </summary>
    public Func<LispObject, LispObject, LispObject, LispObject> __setattr__;
    /// <summary>
    /// Ordering to use when doing lookups on this type. ICons.
    /// </summary>
    public LispObject __mro__;

    /// <summary>
    /// Function to implement Get in the descriptor protocol.
    /// </summary>
    public Func<LispObject, LispObject, LispObject, LispObject> __get__;
    /// <summary>
    /// Function to implement Set (and possibly delete) in the descriptor protocol.
    /// </summary>
    public Func<LispObject, LispObject, LispObject, LispObject> __set__;

    /// <summary>
    /// Methods used to implement comparison for this type.
    /// </summary>
    public ComparisonMethods _comparison_methods;

    /// <summary>
    /// Methods used to implent the Cons-List protocol.
    /// </summary>
    public ListMethods _list_methods;
    /// <summary>
    /// Methods used to implement the Dict protocol.
    /// </summary>
    public MappingMethods _map_methods;

    /// <summary>
    /// The C# Type of instances generated by this type object.
    /// </summary>
    public Type _instance_type;


    // Temporary fix to get type info quicker.
    public override string ToString () {
      return string.Format("(type \"{0}\")", __name__);
    }
  }
}
